version: '3.8'

services:
   node_backend:
      container_name: node_docker
      image: node_docker:0.0.1
      build:
         context: .
      ports:
         - '5000:5000'
      environment:
         - PORT=5000
         - PGDATABASE=my_db
         - PGPASSWORD=ermatov
         - PGUSER=ermatov
         - PGHOST=node_db
      depends_on:
         - node_db
   node_db:
      container_name: node_db
      image: 'postgres:12'
      ports:
         - '5432:5432'
      environment:
         - POSTGRES_USER=ermatov
         - POSTGRES_PASSWORD=ermatov
         - POSTGRES_DB=my_db
      volumes:
         - nps_data:/var/lib/postgresql/data

volumes:
   nps_data: {}
